---
# Source: oes/templates/secrets/opsmx-gitops-secret.yaml
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  gitcloneparam: https://NaveenBalagouni:encrypted%3Agittoken%3Agittoken@github.com/NaveenBalagouni/isdmar27.git

  # Repo details to fetch dynamic configuration
  dynamicaccountsgituri: https://github.com/NaveenBalagouni/isdmar27.git
  gituser: NaveenBalagouni
  gittoken: encrypted:gittoken:gittoken
  dynamicAccRepository: isdmar27

kind: Secret
metadata:
  name: opsmx-gitops-auth
type: Opaque
